export const featuredOffersActions = {
  FETCH_FEATURED_OFFERS_START: "FETCH_FEATURED_OFFERS_START",
  FETCH_FEATURED_OFFERS_SUCCESS: "FETCH_FEATURED_OFFERS_SUCCESS",
  FETCH_FEATURED_OFFERS_FAIL: "FETCH_FEATURED_OFFERS_FAIL",
};

export const allOffersActions = {
  FETCH_ALL_OFFERS_START: "FETCH_ALL_OFFERS_START",
  FETCH_ALL_OFFERS_SUCCESS: "FETCH_ALL_OFFERS_SUCCESS",
  FETCH_ALL_OFFERS_FAIL: "FETCH_ALL_OFFERS_FAIL",
  FETCH_ALL_OFFERS_QUERY: "FETCH_ALL_OFFERS_QUERY",
};

export const userActions = {
  USER_LOGIN_START: "USER_LOGIN_START",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGOUT: "USER_LOGOUT",
  UPDATE_CURRENT_USER_PROFILE_SUCCESS: "UPDATE_CURRENT_USER_PROFILE_SUCCESS",
  CLOSE_CURRENT_USER_PROFILE_NOTIFICATION:
    "CLOSE_CURRENT_USER_PROFILE_NOTIFICATION",
  UPDATE_CURRENT_USER_PASSWORD_SUCCESS: "UPDATE_CURRENT_USER_PASSWORD_SUCCESS",
  USER_PROFILE_ASYNC_START: "USER_PROFILE_ASYNC_START",
  USER_PROFILE_ASYNC_FAIL: "USER_PROFILE_ASYNC_FAIL",
};

export const offerActions = {
  ASYNC_OFFER_START: "ASYNC_OFFER_START",
  ASYNC_OFFER_FAIL: "ASYNC_OFFER_FAIL",
  CREATE_OFFER_SUCCESS: "CREATE_OFFER_SUCCESS",
  FETCH_SINGLE_OFFER_SUCCESS: "FETCH_SINGLE_OFFER_SUCCESS",
  CLOSE_OFFER_ERROR: "CLOSE_OFFER_ERROR",
  DELETE_OFFER_SUCCESS: "DELETE_OFFER_SUCCESS",
};

export const notificationActions = {
  OPEN_NOTIFICATION: "OPEN_NOTIFICATION",
  CLOSE_NOTIFICATION: "CLOSE_NOTIFICATION",
};

export const axiosRequestConfig = {
  headers: {
    "Content-Type": "application/json",
  },
};
